# http://travis-ci.org/#!/gjhiggins/RDFAlchemy
language: python
python:
    - 2.5
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - pypy
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors simplejson; fi
    # - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install --upgrade "https://bitbucket.org/gjhiggins/isodate/downloads/isodate-0.4.8.tar.gz"; pip install --use-mirrors --default-timeout 60 "elementtree"; fi
    - pip install -r requirements.txt --use-mirrors
    - python setup.py build

before_script:
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then flake8 --exit-zero rdfalchemy; fi
script:
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then nosetests; fi
    # Must cd somewhere else ("build/src" in this instance) so Python3 doesn't
    # get confused and run the Python 2 code from the current directory
    # instead of the installed 2to3 translated version.
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then SESAME2_URL="http://bel-epa.com:8080/openrdf-workbench/repositories/otter/query" nosetests --where=build/src; fi
